package pojos;
// Generated Oct 17, 2020 12:29:09 PM by Hibernate Tools 4.3.1

/**
 * Week generated by hbm2java
 */
public class Week implements java.io.Serializable {

    private Integer id;
    private String date;
    private String day;
    private String weather;
    private String temperature;

    public Week() {
    }

    public Week(String date) {
        this.date = date;
    }

    public Week(String date, String day, String weather, String temperature) {
        this.date = date;
        this.day = day;
        this.weather = weather;
        this.temperature = temperature;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDate() {
        return this.date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getDay() {
        return this.day;
    }

    public void setDay(String day) {
        this.day = day;
    }

    public String getWeather() {
        return this.weather;
    }

    public void setWeather(String weather) {
        this.weather = weather;
    }

    public String getTemperature() {
        return this.temperature;
    }

    public void setTemperature(String temperature) {
        this.temperature = temperature;
    }

    @Override
    public String toString() {
        return "Дата: " + date + ", День: " + day + ", Погода: " + weather + ", Температура: " + temperature;
    }

}
